---
  - name: PHP
    apt: name=software-properties-common

  - name: Add co-installable PHP 7.4
    apt_repository: 
     repo: 'ppa:ondrej/php'

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Install PHP Extensions and PyMysql
    apt: name={{item}} state=latest
    with_items:
      - php7.4
      - libapache2-mod-php7.4
      - php7.4-common
      - php7.4-gmp
      - php7.4-curl
      - php7.4-intl
      - php7.4-mbstring
      - php7.4-xmlrpc
      - php7.4-mysql
      - php7.4-gd
      - php7.4-bcmath
      - php7.4-xml
      - php7.4-cli
      - php7.4-zip
      - php7.4-sqlite3
      - php7.4-ldap
      - python3
      - python3-mysqldb
